export { Element as CElement } from './element/element'
export type { IElement } from './element/i_element'
export { Document } from './document/document'
export type { IDocument } from './document/i_document'
export { ElementMgr } from './document/element_mgr'
